# Generated by Django 6.1 on 2026-08-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FADES', 'Fades'), ('TAPERS', 'Tapers'), ('BEARDS', 'Beards'), ('DREADS', 'Dreads'), ('AFROS', 'Afros')], max_length=10)),
                ('image_url', models.URLField(help_text='Link to the hairstyle image')),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
    ]
