# Generated by Django 6.1 on 2026-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='image_url',
        ),
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(default='test.jpg', help_text='Upload hairstyle image', upload_to='styles/'),
            preserve_default=False,
        ),
    ]
