# Generated by Django 6.1 on 2026-08-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_remove_style_image_url_style_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography of the barber'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, help_text='Barber profile photo', null=True, upload_to='barbers/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default='Barber', max_length=100),
        ),
    ]
