# Generated by Django 6.1 on 2026-08-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0008_customer_loyalty_points_alter_staff_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional service image', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='style',
            name='category',
            field=models.CharField(choices=[('FADES', 'Fades'), ('TAPERS', 'Tapers'), ('BEARDS', 'Beards'), ('DREADS', 'Dreads'), ('AFROS', 'Afros'), ('CAESAR', 'Caesar'), ('BOX_FADE', 'Box Fade'), ('NTEGE', 'Ntege (Push Back)'), ('LINE_UP', 'Line Up / Shape Up')], max_length=10),
        ),
    ]
