# Generated by Django 6.1 on 2026-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_service_image_alter_style_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, help_text='Direct image URL', null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.URLField(blank=True, help_text='Direct image URL', null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.URLField(help_text='Direct image URL'),
        ),
    ]
