# Generated by Django 6.1 on 2026-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_alter_service_image_alter_staff_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.RemoveField(
            model_name='style',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Option 2: Upload from device', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Option 1: Paste direct image link', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Option 2: Upload from device', null=True, upload_to='barbers/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image_url',
            field=models.URLField(blank=True, help_text='Option 1: Paste direct image link (Unsplash, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Option 2: Upload from device', null=True, upload_to='styles/'),
        ),
        migrations.AddField(
            model_name='style',
            name='image_url',
            field=models.URLField(blank=True, help_text='Option 1: Paste direct image link', null=True),
        ),
    ]
